using System.Windows.Controls;
using System.Collections.ObjectModel;
using SmartSoldier.Models;

namespace SmartSoldier.Views
{
    public partial class PersonellView : UserControl
    {
        // Ensure dgPersonell is declared if not defined in XAML
        // Remove the manual declaration if dgPersonell is defined in XAML
        // private DataGrid dgPersonell;

        public PersonellView()
        {
            // This method is generated by the XAML designer and should exist if the .xaml and .xaml.cs files match and are partial.
            InitializeComponent();

            // Beispiel-Daten für Anzeige
            var team = new ObservableCollection<Person>
            {
                new Person { Vorname = "Max", Nachname = "Mustermann", Aufgabe = "Späher", Waffe = "Gewehr", IstVerbunden = true },
                new Person { Vorname = "Anna", Nachname = "Schmidt", Aufgabe = "Sanitäterin", Waffe = "Pistole", IstVerbunden = false },
                new Person { Vorname = "Peter", Nachname = "Müller", Aufgabe = "Truppführer", Waffe = "Maschinengewehr", IstVerbunden = true }
            };

            if (this.FindName("dgPersonell") is DataGrid dgPersonell)
            {
                dgPersonell.ItemsSource = team;
            }
        }
    }
}
